### PR TITLE
Remove content-length when using web clients

### LINKED ISSUE #13: Protocol error (promised bytes vs received bytes) when using web / fetch client
**Describe the bug**

I've been building a Flutter app that uses ConnectRPC. Everything was working fine on the MacOS build, but when I tried building and running on the web I started getting protocol errors.

**To Reproduce**

When I try and call my server endpoint, I get: Protocol error: promised 361 bytes, received 408.

The exception itself is coming from length checking in the `toBytes` function in `lib/src/protocol/sink.dart`. I tried removing the length checks, and this does seem to resolve the problem.

Here's the relevant protobuf definitions, I'm calling the login service:
```proto
service TimesheetService {
  rpc Login(LoginRequest) returns (LoginResponse);
...
message LoginResponse {
  User user = 1;
  AuthToken auth_token = 2;
}
...
message User {
  string id = 1;  // UUID
  string email = 2;
  UserRole role = 3;
  string name = 4;
  optional string myob_employee_id = 5;
}
```

Now, here's where I instantiate the client in my codebase:
```dart
// This function is imported by timesheet_service.dart when compiled for web
RemoteTimesheetServiceImpl createRemoteTimesheetService(
    {required String baseUrl}) {
  return RemoteTimesheetServiceImpl(
    baseUrl: baseUrl,
    createTransport: (baseUrl) => protocol.Transport(
      baseUrl: baseUrl,
      codec: const JsonCodec(),
      httpClient: web.createHttpClient(),
    ),
  );
}

```
Interestingly, this doesn't happen for all responses. If I mistype the password, I receive the message back from the server saying the user was not found, so no protocol error there.

**Environment (please complete the following information):**

- connectrpc version: `0.3.0`
- Dart SDK version: `3.5.4`
- Flutter SDK version:  `3.24.5`
- Platform/Device and version: `web`

### PR DESCRIPTION
**Pull request by benridley**
This PR ensures we always remove the content-length & content-encoding headers when using fetch-based HTTP clients.

It was discovered that when performing length checks in the protocol code, the length supplied by these clients was often incorrect because the browser has already performed decompression on the response. By removing these headers when using the web client, we forgo length checks and instead rely on the protocol parsing to validate any malformed responses.

Fixes #13.

### CODE REVIEW

File: packages/connect/lib/src/web.dart [hunk 1]
```diff
@@ -44,12 +44,10 @@ HttpClient createHttpClient() {
...
-    creq.signal?.future.then(
-      (err) {
-        abortErr = err;
-        abortCtrl.abort();
-      },
-    );
+    creq.signal?.future.then((err) {
+      abortErr = err;
+      abortCtrl.abort();
+    });
```
Comment (srikrsna-buf) [inline packages/connect/lib/src/web.dart:50]: This looks like unrelated change can you revert this?

File: packages/connect/lib/src/web.dart [hunk 2]
```diff
@@ -93,11 +93,9 @@ HttpClient createHttpClient() {
...
   Stream<Uint8List> toStream(AbortSignal? signal) async* {
     ConnectException? abortErr;
-    signal?.future.then(
-      (err) {
-        abortErr = err;
-      },
-    );
+    signal?.future.then((err) {
+      abortErr = err;
+    });
```
Comment (srikrsna-buf) [inline packages/connect/lib/src/web.dart:98]: Same as above, unrelated

**Review by srikrsna-buf — COMMENTED** [review]
Looks good! Can you also signoff on the commits?

**Comment by benridley** [comment]
Oops sorry for the noise @srikrsna-buf, I think it must have been auto formatting.

Anyway, I've signed off and removed the unrelated edits. Thanks!

**Review by srikrsna-buf — APPROVED** [review]
